blank_issues_enabled: false
contact_links:
  - name: 💬 Workout Cool Discord
    url: https://discord.gg/NtrsUBuHUB
    about: Please use our Discord server for all questions, discussions, and support.