export const paths = {
  root: "/",
  signUp: "auth/signup",
  signIn: "auth/signin",
  forgotPassword: "auth/forgot-password",
  resetPassword: "auth/reset-password",
  verifyEmail: "auth/verify-email",
  profile: "profile",
  privacy: "/legal/privacy",
  terms: "/legal/terms",
  programs: "/programs",
  exercises: "/exercises",
  progression: "/progression",
  leaderboard: "/leaderboard",
} as const;
