import { NextResponse } from "next/server";

/**
 * DEPRECATED: This endpoint is no longer needed
 * 
 * RevenueCat user ID assignment is now handled automatically:
 * - Anonymous users get an ID generated by RevenueCat
 * - Authenticated users use their BetterAuth user ID via RevenueCat.logIn()
 * 
 * The sync is handled by the /api/revenuecat/sync-status endpoint
 */

export async function POST() {
  return NextResponse.json(
    { 
      error: "This endpoint is deprecated. Use /api/revenuecat/sync-status instead" 
    },
    { status: 410 } // 410 Gone
  );
}

export async function GET() {
  return NextResponse.json(
    { 
      error: "This endpoint is deprecated. RevenueCat IDs are managed automatically" 
    },
    { status: 410 } // 410 Gone
  );
}
