name: Publish Docker GHCR Image

on:
  release:
    types: [published]
  push:
    branches:
      - ci/fix-ghcr-publish

permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "tag=v1.2.4" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build . \
                    --tag ghcr.io/lucasnevespereira/workout-cool:${{ steps.vars.outputs.tag }} \
                    --tag ghcr.io/lucasnevespereira/workout-cool:latest

      - name: Push Docker image (release tag)
        run: docker push ghcr.io/lucasnevespereira/workout-cool:${{ steps.vars.outputs.tag }}

      - name: Push Docker image (latest tag)
        run: docker push ghcr.io/lucasnevespereira/workout-cool:latest
