name: Publish Docker GHCR Image

on:
  push:
    branches:
      - ci/publish-images

permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . \
            --tag ghcr.io/snouzy/workout-cool:${{ github.event.release.tag_name }} \
            --label org.opencontainers.image.source=${{ github.repository }} \
            --label org.opencontainers.image.version=${{ github.event.release.tag_name }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/snouzy/workout-cool:${{ github.event.release.tag_name }}